[package]
name = "marmite"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
tera = "1.12"
comrak = "0.17"
walkdir = "2.3"
chrono = { version = "0.4", features = ["serde"] }

