name: GH Pages Deploy

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:

  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4

      - name: check formatting 🖌️
        run: cargo fmt -- --check

      - name: Cache Cargo dependencies 📦
        uses: Swatinem/rust-cache@v2

      - name: Test 🧪
        run: cargo test

      - name: Build 🔧
        run: cargo build --release

      - name: Add paths 📂
        run: echo "::add-path::$GITHUB_WORKSPACE/target/release"

      - name: Build site 🏗️
        run: marmite example site -vvvv

      - name: List files on site 📂
        run: ls -R site